import type { WorkbenchController as CoreWorkbenchController } from "./useWorkbenchCoreController.js";

export function useOperationsController(core: CoreWorkbenchController) {
  return {
    selectedSkillId: core.selectedSkillId,
    selectedSkillDetail: core.selectedSkillDetail,
    selectedJobId: core.selectedJobId,
    selectedJobDetail: core.selectedJobDetail,
    operationsBusy: core.operationsBusy,
    operationsMessage: core.operationsMessage,
    latestSkillResult: core.latestSkillResult,
    pendingSkillDraft: core.pendingSkillDraft,
    latestCardDrawResult: core.latestCardDrawResult,
    pendingGeneratedSave: core.pendingGeneratedSave,
    styleDistillationProfile: core.styleDistillationProfile,
    disassemblyBooks: core.disassemblyBooks,
    disassemblyLibraryBusy: core.disassemblyLibraryBusy,
    refreshDisassemblyLibrary: core.refreshDisassemblyLibrary,
    archiveDisassemblySource: core.archiveDisassemblySource,
    selectSkill: core.selectSkill,
    refreshSkillCatalog: core.refreshSkillCatalog,
    selectJob: core.selectJob,
    openJobResultFile: core.openJobResultFile,
    continueJobResultInConversation: core.continueJobResultInConversation,
    runJob: core.runJob,
    cancelSelectedJob: core.cancelSelectedJob,
    invokeSelectedSkill: core.invokeSelectedSkill,
    runWorkflowSkill: core.runWorkflowSkill,
    generateCardDraw: core.generateCardDraw,
    selectCardDraw: core.selectCardDraw,
    importSkillFromPath: core.importSkillFromPath,
    uploadSkillFile: core.uploadSkillFile,
    importSkillFromUrl: core.importSkillFromUrl,
    draftSkillPreview: core.draftSkillPreview,
    importPendingSkillDraft: core.importPendingSkillDraft,
    discardPendingSkillDraft: core.discardPendingSkillDraft,
    openSkillFolder: core.openSkillFolder,
    deleteOrDisableSelectedSkill: core.deleteOrDisableSelectedSkill,
    restoreSelectedBuiltinSkill: core.restoreSelectedBuiltinSkill,
    updateSkillDescription: core.updateSkillDescription,
    runNuwaStyleDistillation: core.runNuwaStyleDistillation,
    toggleNuwaStyleDistillation: core.toggleNuwaStyleDistillation,
    deleteNuwaStyleDistillation: core.deleteNuwaStyleDistillation,
    savePendingGenerated: core.savePendingGenerated,
    savePendingGeneratedAsDraft: core.savePendingGeneratedAsDraft,
    copyPendingGeneratedContent: core.copyPendingGeneratedContent,
    discardPendingGenerated: core.discardPendingGenerated,
    restoreGeneratedCache: core.restoreGeneratedCache,
    copyGeneratedCacheContent: core.copyGeneratedCacheContent,
    discardGeneratedCacheRecord: core.discardGeneratedCacheRecord
  };
}
